In [1]:
import os
import sys
import numpy as np

In [ ]:
my_list = [1,2,3,4]

In [ ]:
my_array = np.array(my_list)

In [ ]:
my_array

In [ ]:
dir(my_array)

In [ ]:
str(my_array)

In [ ]:
my_array.dtype

In [ ]:
my_array.dtype = 'float32'

In [ ]:
my_array

In [ ]:
my_array.dtype = "int64"

In [ ]:
my_array

In [ ]:
my_array.dtype = "float64"

In [ ]:
my_array

In [ ]:
my_array.dtype = "int64"

In [ ]:
my_array

In [ ]:
my_array

In [ ]:
np.float32(my_array)

In [ ]:
my_array2 = np.float32(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

In [ ]:
my_array2

In [ ]:
my_array2[1][1]

In [ ]:
my_array2.shape

In [ ]:
my_array3 = np.random.rand(3,3)

In [ ]:
my_array3

In [ ]:
my_array2 + my_array3

In [ ]:
my_array2 * my_array3[:][0]

In [ ]:
my_array2[:,0]

In [ ]:
my_array2[:,0] * my_array3[0]

In [ ]:
my_array2[:,0].shape

In [ ]:
my_array3[0].shape

In [ ]:
np.matmul(my_array2[:,0], my_array3[0])

In [2]:
import pandas as pd

In [ ]:
my_df = pd.DataFrame(my_array2)

In [ ]:
my_df

In [ ]:
my_df.columns = ["zero", "one", "two"]

In [ ]:
my_df

In [ ]:
my_df["zero"]

In [ ]:
my_df.iloc[0]

In [ ]:
my_df * 2

In [ ]:
my_df[my_df["zero"] > 3]

In [ ]:
my_df[(my_df["zero"] * my_df["two"]) < 5]

In [ ]:
my_df["total"] = my_df.sum(axis=1)

In [ ]:
my_df = my_df.drop("total", axis=1)

In [ ]:
my_df

In [ ]:
row_sum = my_df.sum(axis=0)

In [ ]:
row_sum

In [ ]:
my_df['total'] = row_sum

In [ ]:
my_df

In [ ]:
row_sum.index = [0,1,2]

In [ ]:
row_sum

In [ ]:
my_df['total'] = row_sum

In [ ]:
my_df

In [ ]:
str(my_df['total'])

In [ ]:
my_df['total string'] = my_df['total'].astype(int).astype(str)

In [ ]:
my_df

In [ ]:
my_df['total'] + my_df['total string']

In [ ]:
my_df2 = pd.DataFrame({'name': ['Bob', 'Mary', 'Alice'], 'age': [27, 13, 95], 'skill_level': [4.5, 99.2, 45.3]})

In [ ]:
my_df2

In [ ]:
my_df3 = pd.DataFrame(my_array2)

In [ ]:
pd.concat([my_df2, my_df3])

In [ ]:
pd.concat([my_df2, my_df3], axis=1)

In [3]:
student_mat = pd.read_csv("student-mat.csv", sep=";")

In [4]:
student_mat

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [5]:
avg_grade = student_mat['G3'].median()

In [6]:
avg_grade

11.0

In [7]:
student_mat['above_avg'] = (student_mat['G3'] >= avg_grade)

In [8]:
student_mat

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,above_avg
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,3,4,1,1,3,6,5,6,6,False
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,3,1,1,3,4,5,5,6,False
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,2,2,3,3,10,7,8,10,False
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,2,1,1,5,2,15,14,15,True
4,GP,F,16,U,GT3,T,3,3,other,other,...,3,2,1,2,5,4,6,10,10,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,4,4,5,4,11,9,9,9,False
391,MS,M,17,U,LE3,T,3,1,services,services,...,4,5,3,4,2,3,14,16,16,True
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,3,3,3,3,3,10,8,7,False
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,1,3,4,5,0,11,12,10,False
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,2,3,3,3,5,5,8,9,9,False

In [9]:
student_mat['test_inst'] = np.random.randint(0, 100, len(student_mat))

In [10]:
student_mat

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,above_avg,test_inst
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,1,1,3,6,5,6,6,False,73
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,1,1,3,4,5,5,6,False,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,2,2,3,3,10,7,8,10,False,71
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,1,1,5,2,15,14,15,True,28
4,GP,F,16,U,GT3,T,3,3,other,other,...,2,1,2,5,4,6,10,10,False,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,4,4,5,4,11,9,9,9,False,85
391,MS,M,17,U,LE3,T,3,1,services,services,...,5,3,4,2,3,14,16,16,True,8
392,MS,M,21,R,GT3,T,1,1,other,other,...,3,3,3,3,3,10,8,7,False,14
393,MS,M,18,R,LE3,T,3,2,services,other,...,1,3,4,5,0,11,12,10,False,97
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,3,3,5,5,8,9,9,False,41

In [13]:
student_mat_train = student_mat[student_mat['test_inst'] < 80].copy()

In [14]:
student_mat_test = student_mat[student_mat['test_inst'] >= 80].copy()

In [17]:
from chefboost import Chefboost as chef

In [18]:
config = {'algorithm': 'C4.5'}

In [26]:
student_mat_train['above_avg'] = ['true' if x else 'false' for x in student_mat_train['above_avg']]

In [27]:
student_mat_train

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,above_avg,test_inst
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,4,3,4,1,1,3,6,false,73
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,no,5,3,3,1,1,3,4,false,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,no,4,3,2,2,3,3,10,false,71
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,3,2,2,1,1,5,2,true,28
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,4,3,2,1,2,5,4,false,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,MS,F,19,R,GT3,T,2,3,services,other,...,no,5,4,2,1,2,5,0,false,43
389,MS,F,18,U,GT3,T,1,1,other,other,...,no,1,1,1,1,1,5,0,false,52
391,MS,M,17,U,LE3,T,3,1,services,services,...,no,2,4,5,3,4,2,3,true,8
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,5,5,3,3,3,3,3,false,14
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,no,3,2,3,3,3,5,5,false,41

In [20]:
student_mat_train.drop(['G1','G2','G3'], inplace=True, axis=1)

In [21]:
student_mat_train

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,above_avg,test_inst
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,4,3,4,1,1,3,6,0,73
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,no,5,3,3,1,1,3,4,0,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,no,4,3,2,2,3,3,10,0,71
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,3,2,2,1,1,5,2,1,28
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,4,3,2,1,2,5,4,0,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,MS,F,19,R,GT3,T,2,3,services,other,...,no,5,4,2,1,2,5,0,0,43
389,MS,F,18,U,GT3,T,1,1,other,other,...,no,1,1,1,1,1,5,0,0,52
391,MS,M,17,U,LE3,T,3,1,services,services,...,no,2,4,5,3,4,2,3,1,8
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,5,5,3,3,3,3,3,0,14
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,no,3,2,3,3,3,5,5,0,41

In [28]:
config = {'algorithm': 'C4.5'}
model = chef.fit(student_mat_train, config = config, target_label = 'above_avg')

26-02-05 13:48:13 - C4.5 tree is going to be built...
26-02-05 13:48:15 - -------------------------
26-02-05 13:48:15 - finished in 1.7922632694244385 seconds
26-02-05 13:48:15 - -------------------------
26-02-05 13:48:15 - Evaluate train set
26-02-05 13:48:15 - -------------------------
26-02-05 13:48:15 - Accuracy: 62.0% on 300 instances
26-02-05 13:48:15 - Labels: ['false' 'true']
26-02-05 13:48:15 - Confusion matrix: [[24, 5], [109, 162]]
26-02-05 13:48:15 - Precision: 82.7586%, Recall: 18.0451%, F1: 29.6296%

In [29]:
student_mat_train.drop(['failures'], inplace=True, axis=1)

In [30]:
config = {'algorithm': 'C4.5'}
model = chef.fit(student_mat_train, config = config, target_label = 'above_avg')

26-02-05 13:48:41 - C4.5 tree is going to be built...
26-02-05 13:48:43 - -------------------------
26-02-05 13:48:43 - finished in 2.024278402328491 seconds
26-02-05 13:48:43 - -------------------------
26-02-05 13:48:43 - Evaluate train set
26-02-05 13:48:43 - -------------------------
26-02-05 13:48:43 - Accuracy: 61.333333333333336% on 300 instances
26-02-05 13:48:43 - Labels: ['false' 'true']
26-02-05 13:48:43 - Confusion matrix: [[24, 7], [109, 160]]
26-02-05 13:48:43 - Precision: 77.4194%, Recall: 18.0451%, F1: 29.2683%

In [31]:
student_mat_test['above_avg'] = ['true' if x else 'false' for x in student_mat_test['above_avg']]

In [32]:
student_mat_test.drop(['G1','G2','G3','failures'], inplace=True, axis=1)

In [33]:
student_mat_train.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher',
       'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc',
       'health', 'absences', 'above_avg', 'test_inst'],
      dtype='object')

In [34]:
student_mat_test.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher',
       'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc',
       'health', 'absences', 'above_avg', 'test_inst'],
      dtype='object')

In [39]:
chef.evaluate(model, student_mat_test, target_label='above_avg')

26-02-05 13:53:46 - -------------------------
26-02-05 13:53:46 - Evaluate test set
26-02-05 13:53:46 - -------------------------
26-02-05 13:53:46 - Accuracy: 44.21052631578947% on 95 instances
26-02-05 13:53:46 - Labels: ['true' 'false']
26-02-05 13:53:46 - Confusion matrix: [[40, 51], [2, 2]]
26-02-05 13:53:46 - Precision: 43.956%, Recall: 95.2381%, F1: 60.1503%

{'Accuracy': 44.21052631578947,
 'Instances': 95,
 'Labels': array(['true', 'false'], dtype=object),
 'Confusion matrix': [[40, 51], [2, 2]],
 'Precision': 43.956,
 'Recall': 95.2381,
 'F1': 60.1503}

In [37]:
dir(chef)

['Any',
 'Dict',
 'Logger',
 'Optional',
 'Training',
 'Union',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'adaboost_clf',
 'cb_eval',
 'evaluate',
 'feature_importance',
 'fit',
 'functions',
 'gbm',
 'json',
 'load_model',
 'logger',
 'np',
 'os',
 'pd',
 'pickle',
 'predict',
 'randomforest',
 'restoreTree',
 'save_model',
 'time']

In [38]:
help(chef.evaluate)

Help on function evaluate in module chefboost.Chefboost:

evaluate(model: dict, df: pandas.core.frame.DataFrame, target_label: str = 'Decision', task: str = 'test', silent: bool = False) -> dict
    Evaluate the performance of a built model on a data set
    Args:
        model (dict): built model which is the output of fit function
        df (pandas data frame): data frame you would like to evaluate
        target_label (str): target label
        task (string): set this to train, validation or test
        silent (bool): set this to True if you do not want to see
            any informative logs
    Returns:
        evaluation results (dict)